version: "3.8"

services:

  db:
    image: timescale/timescaledb:latest-pg14
    container_name: master_timescaledb
    environment:
      POSTGRES_DB: kernelX
      POSTGRES_USER: kernelX
      POSTGRES_PASSWORD: kernelX
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mqtt-service:
    build: .
    container_name: mqtt-subscriber-service
    ports:
      - "8091:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/kernelX
      SPRING_DATASOURCE_USERNAME: kernelX
      SPRING_DATASOURCE_PASSWORD: kernelX

volumes:
  db_data: