#spring:
#  datasource:
##    url: jdbc:postgresql://localhost:5432/mqtt_sensor_data
#    url: jdbc:postgresql://host.docker.internal:5432/mqtt_sensor_data
#    username: postgres
#    password: postgres
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mqtt_sensor_data
    username: postgres
    password: postgres
    hikari:
      initialization-fail-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update   # change to validate later in production
    properties:
      hibernate:
        format_sql: true
    show-sql: false

mqtt:
  broker: tcp://broker.hivemq.com:1883
  client-id: spring-mqtt-consumer
  topic: thw/telemetry/#
  qos: 1
